[package]
name = "visim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
gl_debug = ["gl/debug"]

[dependencies]
sdl2 = "0.35.2"
gl = { path = "gl" }
